#!/bin/bash

MYHOME="`dirname \"$0\"`" # Relative
export MYHOME="`( cd \"$MYHOME\" && pwd )`" # Absolutized and normalized
#cd $MYHOME

export PYTHON_EXE=python
# /usr/bin - dos2unix / unix2dos
#export FLIP=dos2unix 
export FLIP=./tools/flip/flip.linux-static
export GREP="egrep -lUIr $'\r'\$"

# We can build Linux installer on Mac OSX, check if this is the case here
unamestr=`uname`
if [[ "$unamestr" == 'Darwin' ]]; then
  export FLIP=./tools/ConvertNewlines.app/Contents/Resources/flip
  export GREP='grep -lUIr "\r"'
fi

if [ ! -d temp ]; then
	mkdir temp
fi
rm -Rf temp/*
