#!/usr/bin/env bash

[[ ! -d ~/Library/Application\ Support/Autodesk/ApplicationPlugins ]] && mkdir -p ~/Library/Application\ Support/Autodesk/ApplicationPlugins
ln -s ~/Library/Containers/com.autodesk.mas.fusion360/Data/Library/Application\ Support/Autodesk/ApplicationPlugins/{{BUNDLE}} ~/Library/Application\ Support/Autodesk/ApplicationPlugins/{{BUNDLE}}

exit 0